### PR TITLE
Feature login register

### PR DESCRIPTION
**Pull request by Xiro234**
Login and register page are finished, they are linked to each other as well.

### CODE REVIEW

**Review by bnguye1 — APPROVED** [review]
Looks good, and since develop didn't have a .gitignore file, we can delete the .idea folder afterwards

**Review by lazerw — APPROVED** [review]
Looks great.

**Comment by Xiro234** [comment]
Currently, there are no tests written for this url, this will be done in the next iteration.
image
This is an image of how the url looks at the moment with some temporary images.

**Comment by bnguye1** [comment]
Currently, there is no unit tests for the login page, so the unit test will be created next iteration.
image

This is an image of how the url looks at the moment with some temporary images.

**Pull request merged**
