### PR TITLE
Feature navbar

### PR DESCRIPTION
**Pull request by lazerw**
I created a navigation bar, which is primarily located in the navbar.html file within "templates". The bar links to our current pages, most of which are empty thus far. Includes some fantastic temporary images while we wait for our logo.

### CODE REVIEW

**Comment by Xiro234** [comment]
Navbar is functional and able to be expanded if needed. Merging.

**Comment by Xiro234** [comment]
Pycache and other local files will be removed later.

**Review by bnguye1 — APPROVED** [review]
Looks good, and we can delete the pycache files later

**Comment by lazerw** [comment]
My only sizing error was that I did not end up getting to write a test for the navigation bar. Included below is an image of the bar loading correctly. I will complete this story by writing these tests in the next iteration.

**Pull request merged**
